# -----------------------------------------------------------
# IMPORTS
# -----------------------------------------------------------

# APIRouter → used to create route groups in FastAPI
# Depends → used for dependency injection (ex: database session)
# HTTPException → used to return custom HTTP error responses
from fastapi import APIRouter, Depends, HTTPException

# Session → SQLAlchemy database session used for DB operations
from sqlalchemy.orm import Session

# or_ → SQLAlchemy operator used to combine multiple conditions with OR
from sqlalchemy import or_

# get_db → dependency that provides a database session
# It usually opens a DB connection and closes it after request finishes
from database.database import get_db

# Employee → SQLAlchemy ORM model representing the employee table
from models.employee import Employee


# Importing Pydantic schemas used for validation and response formatting
from schemas.employee_schema import (

    # Used when creating a new employee
    # Defines required fields in request body
    EmployeeCreate,

    # Used when updating employee completely (PUT request)
    EmployeeUpdate,

    # Used when partially updating employee (PATCH request)
    EmployeePartialUpdate,

    # Used as response model to control output structure
    EmployeeResponse
)
from models.employee_skill import EmployeeSkill
from models.skill import Skill
from schemas.employee_skill_schema import (
    EmployeeSkillCreate,
    EmployeeSkillResponse
)


# -----------------------------------------------------------
# ROUTER CONFIGURATION
# -----------------------------------------------------------

# APIRouter groups related endpoints together
# prefix="/employees" → all endpoints start with /employees
# tags=["Employees"] → used in Swagger documentation
router = APIRouter(prefix="/employees", tags=["Employees"])



# -----------------------------------------------------------
# CREATE EMPLOYEE
# -----------------------------------------------------------

@router.post(
    "/",                      # endpoint path → /employees/
    status_code=201,          # HTTP status code returned on success
    response_model=EmployeeResponse   # response will follow this schema
)
def add_employee(
    employee: EmployeeCreate,            # request body schema
    db: Session = Depends(get_db)        # dependency injection for DB session
):
    """
    Create a new employee in the database.

    Request Body Example:
    {
        "firstname": "John",
        "lastname": "Doe",
        "email": "john@example.com",
        "experience": 5
    }

    Response Example:
    {
        "id": 1,
        "firstname": "John",
        "lastname": "Doe",
        "email": "john@example.com",
        "experience": 5
    }
    """

    # Convert Pydantic schema to dictionary
    # model_dump() converts validated data to python dict
    new_employee = Employee(**employee.model_dump())

    # Add new record to database session
    db.add(new_employee)

    # Commit transaction → actually writes data to DB
    db.commit()

    # Refresh object → loads updated data (like autogenerated ID)
    db.refresh(new_employee)

    # Return created employee
    return new_employee



# -----------------------------------------------------------
# GET ALL EMPLOYEES
# -----------------------------------------------------------

@router.get(
    "/", 
    response_model=list[EmployeeResponse]
)
def get_employees(db: Session = Depends(get_db)):
    """
    Fetch all employees from database.

    Endpoint:
    GET /employees/

    Response Example:
    [
        {
            "id": 1,
            "firstname": "John",
            "lastname": "Doe"
        },
        {
            "id": 2,
            "firstname": "Jane",
            "lastname": "Smith"
        }
    ]
    """

    # Query all employee records from database
    employees = db.query(Employee).all()

    # Return list of employees
    return employees



# -----------------------------------------------------------
# SEARCH EMPLOYEE BY NAME
# -----------------------------------------------------------

@router.get(
    "/search",
    response_model=list[EmployeeResponse]
)
def search_employee(query: str, db: Session = Depends(get_db)):
    """
    Search employees by firstname or lastname.

    Endpoint:
    GET /employees/search?query=john

    Query Parameter:
    query → text to search

    Example Request:
    /employees/search?query=john

    Response Example:
    [
        {
            "id": 1,
            "firstname": "John",
            "lastname": "Doe"
        }
    ]
    """

    # SQLAlchemy filter using OR condition
    # ilike → case insensitive search
    employees = db.query(Employee).filter(
        or_(
            Employee.firstname.ilike(f"%{query}%"),
            Employee.lastname.ilike(f"%{query}%")
        )
    ).all()

    return employees



# -----------------------------------------------------------
# GET EMPLOYEE BY ID
# -----------------------------------------------------------

@router.get(
    "/{eid}",
    response_model=EmployeeResponse
)
def get_employee(eid: int, db: Session = Depends(get_db)):
    """
    Fetch a single employee using employee ID.

    Endpoint:
    GET /employees/{eid}

    Example:
    /employees/5

    Response Example:
    {
        "id": 5,
        "firstname": "Alice",
        "lastname": "Brown"
    }

    Error Response:
    {
        "detail": "Employee not found"
    }
    """

    # db.get() retrieves record by primary key
    emp = db.get(Employee, eid)

    # If employee does not exist → raise HTTP 404 error
    if emp is None:
        raise HTTPException(status_code=404, detail="Employee not found")

    return emp



# -----------------------------------------------------------
# UPDATE EMPLOYEE (FULL UPDATE)
# -----------------------------------------------------------

@router.put(
    "/{eid}",
    response_model=EmployeeResponse
)
def update_employee(
    eid: int,
    employee: EmployeeUpdate,
    db: Session = Depends(get_db)
):
    """
    Fully update an employee record.

    HTTP Method:
    PUT → replaces the entire resource

    Endpoint:
    PUT /employees/{eid}

    Request Body Example:
    {
        "firstname": "NewName",
        "lastname": "Updated",
        "experience": 6
    }

    Response Example:
    {
        "id": 1,
        "firstname": "NewName",
        "lastname": "Updated",
        "experience": 6
    }
    """

    # Fetch employee by ID
    emp = db.get(Employee, eid)

    if emp is None:
        raise HTTPException(status_code=404, detail="Employee not found")

    # Convert Pydantic model to dictionary
    # model_dump() returns all fields
    for key, value in employee.model_dump().items():

        # setattr dynamically sets attribute
        # Example:
        # setattr(emp, "firstname", "John")
        setattr(emp, key, value)

    # Save changes
    db.commit()

    # Refresh updated object
    db.refresh(emp)

    return emp



# -----------------------------------------------------------
# PARTIAL UPDATE EMPLOYEE
# -----------------------------------------------------------

@router.patch(
    "/{eid}",
    response_model=EmployeeResponse
)
def update_employee_partial(
    eid: int,
    employee: EmployeePartialUpdate,
    db: Session = Depends(get_db)
):
    """
    Partially update an employee.

    HTTP Method:
    PATCH → updates only provided fields

    Endpoint:
    PATCH /employees/{eid}

    Request Example:
    {
        "firstname": "UpdatedName"
    }

    Only firstname will be updated.
    """

    emp = db.get(Employee, eid)

    if emp is None:
        raise HTTPException(status_code=404, detail="Employee not found")

    # exclude_unset=True → only fields provided in request body
    update_data = employee.model_dump(exclude_unset=True)

    for key, value in update_data.items():
        setattr(emp, key, value)

    db.commit()
    db.refresh(emp)

    return emp



# -----------------------------------------------------------
# DELETE EMPLOYEE
# -----------------------------------------------------------

@router.delete("/{eid}")
def delete_employee(eid: int, db: Session = Depends(get_db)):
    """
    Delete employee from database.

    Endpoint:
    DELETE /employees/{eid}

    Example:
    DELETE /employees/5

    Success Response:
    {
        "message": "Employee 5 deleted successfully"
    }

    Error Response:
    {
        "detail": "Employee not found"
    }
    """

    # Fetch employee
    emp = db.get(Employee, eid)

    if emp is None:
        raise HTTPException(status_code=404, detail="Employee not found")

    # Delete record
    db.delete(emp)

    # Commit deletion
    db.commit()

    return {"message": f"Employee {eid} deleted successfully"}

@router.post("/{eid}/skills", response_model=EmployeeSkillResponse)
def add_skill_to_employee(
    eid: int,
    skill: EmployeeSkillCreate,
    db: Session = Depends(get_db)
):
    # Check employee
    emp = db.get(Employee, eid)
    if not emp:
        raise HTTPException(status_code=404, detail="Employee not found")

    # Check skill
    skill_obj = db.get(Skill, skill.skill_id)
    if not skill_obj:
        raise HTTPException(status_code=404, detail="Skill not found")

    # Prevent duplicate
    existing = db.query(EmployeeSkill).filter_by(
        eid=eid,
        skill_id=skill.skill_id
    ).first()

    if existing:
        raise HTTPException(status_code=400, detail="Skill already assigned")

    emp_skill = EmployeeSkill(
        eid=eid,
        skill_id=skill.skill_id,
        proficiency_level=skill.proficiency_level
    )

    db.add(emp_skill)
    db.commit()
    db.refresh(emp_skill)

    return emp_skill

@router.get("/{eid}/skills", response_model=list[EmployeeSkillResponse])
def get_employee_skills(eid: int, db: Session = Depends(get_db)):

    emp = db.get(Employee, eid)
    if not emp:
        raise HTTPException(status_code=404, detail="Employee not found")

    return db.query(EmployeeSkill).filter_by(eid=eid).all()


@router.delete("/{eid}/skills/{skill_id}")
def remove_skill_from_employee(
    eid: int,
    skill_id: int,
    db: Session = Depends(get_db)
):
    emp_skill = db.query(EmployeeSkill).filter_by(
        eid=eid,
        skill_id=skill_id
    ).first()

    if not emp_skill:
        raise HTTPException(status_code=404, detail="Mapping not found")

    db.delete(emp_skill)
    db.commit()

    return {"message": "Skill removed"}


@router.get("/{eid}/skills/details")
def get_employee_skill_details(eid: int, db: Session = Depends(get_db)):

    result = db.query(
        EmployeeSkill.skill_id,
        Skill.skill_name,
        EmployeeSkill.proficiency_level
    ).join(Skill).filter(EmployeeSkill.eid == eid).all()

    return result